import { CommonModule } from '@angular/common';
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { AgGridAngular, AgGridModule } from 'ag-grid-angular';
import { ColDef, GridApi, GridReadyEvent } from 'ag-grid-community';
import { AreaService } from 'src/app/core/Service/areaService';
import { LeadService } from 'src/app/core/Service/LeadService';
import { OrderService } from 'src/app/core/Service/OrderService ';


@Component({
    selector: 'app-lead-list',
    imports: [AgGridModule, CommonModule],
    templateUrl: './lead.report.component.html',
    styleUrls: ['./lead.report.component.scss']
})

export class LeadReportComponent implements OnInit {
    @ViewChild('agGrid') agGrid!: AgGridAngular;

    columnDefs: ColDef[] = [];
    rowData: any[] = [];
    departments : any[] = [];
    reportToList : any[] = [];
    defaultColDef: ColDef = {
        flex: 1,
        minWidth: 100,
        resizable: true,
        sortable: true,
        filter: true,
    };
    allCities: any[] = [];

    private gridApi!: GridApi;
    loading = true;
    error: string | null = null;

    constructor(
        private router: Router,
        private leadservice: LeadService,
        private areaService: AreaService
    ) { }

    ngOnInit(): void {
        this.setupColumnDefs();
        this.loadLead();
        this.loadAllCitiesAndLeads();
    }

    setupColumnDefs(): void {
        this.columnDefs = [
            { headerName: 'Name', field: 'firstName', width: 100 },
            { headerName: 'City', field: 'cityName', width: 80 },
            { headerName: 'Product', field: 'product', width: 80 },
            { headerName: 'Amount', field: 'annualRevenue', width: 80 },
            { headerName: 'Status', field: 'leadStatus', width: 80 },
            { headerName: 'Closure date', field: 'estimatedClosureDate', width: 80 },
            { headerName: 'Generated By', field: 'userEmail', width: 80 },
        ];
    }


    onGridReady(params: GridReadyEvent): void {
        this.gridApi = params.api;
        setTimeout(() => this.gridApi.sizeColumnsToFit(), 0);
    }

loadAllCitiesAndLeads(): void {
        this.loading = true;
        this.areaService.getAllCities().subscribe({
            next: (cities) => {
                this.allCities = cities;
                this.loadLead();  // now call loadLead only after cities are loaded
            },
            error: (err) => {
                console.error('Error loading all cities:', err);
                this.loading = false;
            }
        });
    }

loadLead(): void {
        this.loading = true;
        this.leadservice.getAllBussinessDAta().subscribe({
            next: (data) => {
                this.rowData = data.map(item => {
                    const city = this.allCities.find(c => c.cityId === item.cityId);
                    return {
                        ...item,
                        cityName: city ? city.cityName : ''
                    };
                });
                this.loading = false;
            },
            error: (err) => {
                this.error = 'Error loading leads';
                console.error(err);
                this.loading = false;
            }
        });
    }
    // createNewEnqury(): void {
    //     this.router.navigate(['/Mainlayout/order-create']);
    // }

}
